name = "tableX"
product-name = "tableX"
version = "0.0.1"
identifier = "io.tablex.app"
description = "A desktop PostgreSQL database management application"
binaries = [{ path = "tableX", main = true }]
binaries-dir = "target/release"
out-dir = "dist"
formats = ["deb"]

[linux]
generate-desktop-entry = true
